logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG

server:
  port: 5678
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meu_banco
    username: caixa_adm
    password: 162619
    hikari:
      pool-name: SpringBootHikariCP
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate # Melhor que 'none' para produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          validation:
            mode: none

jwt:
  secret: "minhaChueveSecretaMuitoSegura1234567890" # Armazene isso de forma segura!
  expiration: 3600000 # 1 hora